### ISSUE TITLE
How can control the actual hand by using rviz interactive markers 

### ISSUE THREAD

**Issue by Abduoit** [rst-tu-dortmund/phantomx_rst#2]
Hi

I did successfully compile the repo in ros indigo and ubuntu 16.04

I run the following codes including the control example and rviz. However, the actual hand is not moving it only goes for initial position when I run `roslaunch phantomx_rst arm.launch`

How can I control the actual hand by using rviz interactive markers ??? any help please 

```
sudo chmod 777 /dev/ttyUSB0   
roslaunch phantomx_rst arm.launch
roslaunch phantomx_rst arm_sim.launch
roslaunch phantomx_rst arm_rviz.launch
roslaunch phantomx_rst move_group.launch
rosrun phantomx_control moveit_control
```

**Comment by croesmann** [comment]
sorry, this package is deprecated in favor of [pxpincher_ros](https://github.com/rst-tu-dortmund/pxpincher_ros).
But you should better not start the real arm and arm_sim simultaneously.

I close this issue for now.

Cheers,
Christoph
